// Country dial codes (ITU) — name + dial code (E.164 country code, no leading +)
export interface DialCode { name: string; code: string; iso: string }

export const DIAL_CODES: DialCode[] = [
  { name: "Afghanistan", iso: "AF", code: "93" },
  { name: "Albania", iso: "AL", code: "355" },
  { name: "Algeria", iso: "DZ", code: "213" },
  { name: "Andorra", iso: "AD", code: "376" },
  { name: "Angola", iso: "AO", code: "244" },
  { name: "Argentina", iso: "AR", code: "54" },
  { name: "Armenia", iso: "AM", code: "374" },
  { name: "Australia", iso: "AU", code: "61" },
  { name: "Austria", iso: "AT", code: "43" },
  { name: "Azerbaijan", iso: "AZ", code: "994" },
  { name: "Bahamas", iso: "BS", code: "1242" },
  { name: "Bahrain", iso: "BH", code: "973" },
  { name: "Bangladesh", iso: "BD", code: "880" },
  { name: "Barbados", iso: "BB", code: "1246" },
  { name: "Belarus", iso: "BY", code: "375" },
  { name: "Belgium", iso: "BE", code: "32" },
  { name: "Belize", iso: "BZ", code: "501" },
  { name: "Benin", iso: "BJ", code: "229" },
  { name: "Bhutan", iso: "BT", code: "975" },
  { name: "Bolivia", iso: "BO", code: "591" },
  { name: "Bosnia and Herzegovina", iso: "BA", code: "387" },
  { name: "Botswana", iso: "BW", code: "267" },
  { name: "Brazil", iso: "BR", code: "55" },
  { name: "Brunei", iso: "BN", code: "673" },
  { name: "Bulgaria", iso: "BG", code: "359" },
  { name: "Burkina Faso", iso: "BF", code: "226" },
  { name: "Burundi", iso: "BI", code: "257" },
  { name: "Cambodia", iso: "KH", code: "855" },
  { name: "Cameroon", iso: "CM", code: "237" },
  { name: "Canada", iso: "CA", code: "1" },
  { name: "Cape Verde", iso: "CV", code: "238" },
  { name: "Central African Republic", iso: "CF", code: "236" },
  { name: "Chad", iso: "TD", code: "235" },
  { name: "Chile", iso: "CL", code: "56" },
  { name: "China", iso: "CN", code: "86" },
  { name: "Colombia", iso: "CO", code: "57" },
  { name: "Comoros", iso: "KM", code: "269" },
  { name: "Congo", iso: "CG", code: "242" },
  { name: "Costa Rica", iso: "CR", code: "506" },
  { name: "Croatia", iso: "HR", code: "385" },
  { name: "Cuba", iso: "CU", code: "53" },
  { name: "Cyprus", iso: "CY", code: "357" },
  { name: "Czech Republic", iso: "CZ", code: "420" },
  { name: "Denmark", iso: "DK", code: "45" },
  { name: "Djibouti", iso: "DJ", code: "253" },
  { name: "Dominican Republic", iso: "DO", code: "1809" },
  { name: "Ecuador", iso: "EC", code: "593" },
  { name: "Egypt", iso: "EG", code: "20" },
  { name: "El Salvador", iso: "SV", code: "503" },
  { name: "Estonia", iso: "EE", code: "372" },
  { name: "Eswatini", iso: "SZ", code: "268" },
  { name: "Ethiopia", iso: "ET", code: "251" },
  { name: "Fiji", iso: "FJ", code: "679" },
  { name: "Finland", iso: "FI", code: "358" },
  { name: "France", iso: "FR", code: "33" },
  { name: "Gabon", iso: "GA", code: "241" },
  { name: "Gambia", iso: "GM", code: "220" },
  { name: "Georgia", iso: "GE", code: "995" },
  { name: "Germany", iso: "DE", code: "49" },
  { name: "Ghana", iso: "GH", code: "233" },
  { name: "Greece", iso: "GR", code: "30" },
  { name: "Guatemala", iso: "GT", code: "502" },
  { name: "Guinea", iso: "GN", code: "224" },
  { name: "Guyana", iso: "GY", code: "592" },
  { name: "Haiti", iso: "HT", code: "509" },
  { name: "Honduras", iso: "HN", code: "504" },
  { name: "Hong Kong", iso: "HK", code: "852" },
  { name: "Hungary", iso: "HU", code: "36" },
  { name: "Iceland", iso: "IS", code: "354" },
  { name: "India", iso: "IN", code: "91" },
  { name: "Indonesia", iso: "ID", code: "62" },
  { name: "Iran", iso: "IR", code: "98" },
  { name: "Iraq", iso: "IQ", code: "964" },
  { name: "Ireland", iso: "IE", code: "353" },
  { name: "Israel", iso: "IL", code: "972" },
  { name: "Italy", iso: "IT", code: "39" },
  { name: "Ivory Coast", iso: "CI", code: "225" },
  { name: "Jamaica", iso: "JM", code: "1876" },
  { name: "Japan", iso: "JP", code: "81" },
  { name: "Jordan", iso: "JO", code: "962" },
  { name: "Kazakhstan", iso: "KZ", code: "7" },
  { name: "Kenya", iso: "KE", code: "254" },
  { name: "Kuwait", iso: "KW", code: "965" },
  { name: "Kyrgyzstan", iso: "KG", code: "996" },
  { name: "Laos", iso: "LA", code: "856" },
  { name: "Latvia", iso: "LV", code: "371" },
  { name: "Lebanon", iso: "LB", code: "961" },
  { name: "Lesotho", iso: "LS", code: "266" },
  { name: "Liberia", iso: "LR", code: "231" },
  { name: "Libya", iso: "LY", code: "218" },
  { name: "Liechtenstein", iso: "LI", code: "423" },
  { name: "Lithuania", iso: "LT", code: "370" },
  { name: "Luxembourg", iso: "LU", code: "352" },
  { name: "Macau", iso: "MO", code: "853" },
  { name: "Madagascar", iso: "MG", code: "261" },
  { name: "Malawi", iso: "MW", code: "265" },
  { name: "Malaysia", iso: "MY", code: "60" },
  { name: "Maldives", iso: "MV", code: "960" },
  { name: "Mali", iso: "ML", code: "223" },
  { name: "Malta", iso: "MT", code: "356" },
  { name: "Mauritania", iso: "MR", code: "222" },
  { name: "Mauritius", iso: "MU", code: "230" },
  { name: "Mexico", iso: "MX", code: "52" },
  { name: "Moldova", iso: "MD", code: "373" },
  { name: "Monaco", iso: "MC", code: "377" },
  { name: "Mongolia", iso: "MN", code: "976" },
  { name: "Montenegro", iso: "ME", code: "382" },
  { name: "Morocco", iso: "MA", code: "212" },
  { name: "Mozambique", iso: "MZ", code: "258" },
  { name: "Myanmar", iso: "MM", code: "95" },
  { name: "Namibia", iso: "NA", code: "264" },
  { name: "Nepal", iso: "NP", code: "977" },
  { name: "Netherlands", iso: "NL", code: "31" },
  { name: "New Zealand", iso: "NZ", code: "64" },
  { name: "Nicaragua", iso: "NI", code: "505" },
  { name: "Niger", iso: "NE", code: "227" },
  { name: "Nigeria", iso: "NG", code: "234" },
  { name: "North Korea", iso: "KP", code: "850" },
  { name: "North Macedonia", iso: "MK", code: "389" },
  { name: "Norway", iso: "NO", code: "47" },
  { name: "Oman", iso: "OM", code: "968" },
  { name: "Pakistan", iso: "PK", code: "92" },
  { name: "Palestine", iso: "PS", code: "970" },
  { name: "Panama", iso: "PA", code: "507" },
  { name: "Papua New Guinea", iso: "PG", code: "675" },
  { name: "Paraguay", iso: "PY", code: "595" },
  { name: "Peru", iso: "PE", code: "51" },
  { name: "Philippines", iso: "PH", code: "63" },
  { name: "Poland", iso: "PL", code: "48" },
  { name: "Portugal", iso: "PT", code: "351" },
  { name: "Qatar", iso: "QA", code: "974" },
  { name: "Romania", iso: "RO", code: "40" },
  { name: "Russia", iso: "RU", code: "7" },
  { name: "Rwanda", iso: "RW", code: "250" },
  { name: "Saudi Arabia", iso: "SA", code: "966" },
  { name: "Senegal", iso: "SN", code: "221" },
  { name: "Serbia", iso: "RS", code: "381" },
  { name: "Seychelles", iso: "SC", code: "248" },
  { name: "Sierra Leone", iso: "SL", code: "232" },
  { name: "Singapore", iso: "SG", code: "65" },
  { name: "Slovakia", iso: "SK", code: "421" },
  { name: "Slovenia", iso: "SI", code: "386" },
  { name: "Somalia", iso: "SO", code: "252" },
  { name: "South Africa", iso: "ZA", code: "27" },
  { name: "South Korea", iso: "KR", code: "82" },
  { name: "Spain", iso: "ES", code: "34" },
  { name: "Sri Lanka", iso: "LK", code: "94" },
  { name: "Sudan", iso: "SD", code: "249" },
  { name: "Sweden", iso: "SE", code: "46" },
  { name: "Switzerland", iso: "CH", code: "41" },
  { name: "Syria", iso: "SY", code: "963" },
  { name: "Taiwan", iso: "TW", code: "886" },
  { name: "Tajikistan", iso: "TJ", code: "992" },
  { name: "Tanzania", iso: "TZ", code: "255" },
  { name: "Thailand", iso: "TH", code: "66" },
  { name: "Togo", iso: "TG", code: "228" },
  { name: "Trinidad and Tobago", iso: "TT", code: "1868" },
  { name: "Tunisia", iso: "TN", code: "216" },
  { name: "Turkey", iso: "TR", code: "90" },
  { name: "Turkmenistan", iso: "TM", code: "993" },
  { name: "Uganda", iso: "UG", code: "256" },
  { name: "Ukraine", iso: "UA", code: "380" },
  { name: "United Arab Emirates", iso: "AE", code: "971" },
  { name: "United Kingdom", iso: "GB", code: "44" },
  { name: "United States", iso: "US", code: "1" },
  { name: "Uruguay", iso: "UY", code: "598" },
  { name: "Uzbekistan", iso: "UZ", code: "998" },
  { name: "Venezuela", iso: "VE", code: "58" },
  { name: "Vietnam", iso: "VN", code: "84" },
  { name: "Yemen", iso: "YE", code: "967" },
  { name: "Zambia", iso: "ZM", code: "260" },
  { name: "Zimbabwe", iso: "ZW", code: "263" },
];

export const INDUSTRIES = [
  "Information Technology", "Software / SaaS", "Telecommunications",
  "Banking & Finance", "Insurance", "Accounting",
  "Healthcare & Hospital", "Pharmaceutical", "Biotechnology",
  "Education & Training", "Research",
  "Manufacturing", "Automotive", "Aerospace", "Electronics",
  "Construction", "Real Estate", "Architecture", "Civil Engineering",
  "Oil & Gas", "Energy & Utilities", "Mining",
  "Retail & E-commerce", "FMCG", "Wholesale", "Logistics & Supply Chain",
  "Hospitality & Hotels", "Restaurants & Food Service", "Travel & Tourism",
  "Aviation", "Shipping & Marine", "Transportation",
  "Media & Entertainment", "Marketing & Advertising", "Publishing",
  "Legal", "Consulting", "Human Resources",
  "Government & Public Sector", "Non-Profit / NGO",
  "Agriculture", "Textile & Apparel", "Security Services",
  "Beauty & Wellness", "Sports & Recreation", "Other",
];
