// Translation system for the website
// Keys match EditableText IDs and common UI strings

type TranslationMap = Record<string, Record<string, string>>;

export const translations: TranslationMap = {
  // Navigation & common
  "nav.home": { en: "Home", es: "Inicio", fr: "Accueil", de: "Startseite", it: "Home", pt: "Início", hi: "होम", ta: "முகப்பு", te: "హోమ్", ml: "ഹോം", kn: "ಮುಖಪುಟ", bn: "হোম", ur: "ہوم", ar: "الرئيسية", fa: "خانه", tr: "Ana Sayfa", ru: "Главная", zh: "首页", ja: "ホーム", ko: "홈", th: "หน้าแรก", vi: "Trang chủ", id: "Beranda", ms: "Laman Utama", tl: "Bahay", sw: "Nyumbani", nl: "Home", pl: "Strona główna", el: "Αρχική" },
  "nav.our_services": { en: "Our Services", es: "Nuestros Servicios", fr: "Nos Services", de: "Unsere Dienstleistungen", it: "I Nostri Servizi", pt: "Nossos Serviços", hi: "हमारी सेवाएं", ta: "எங்கள் சேவைகள்", te: "మా సేవలు", ml: "ഞങ്ങളുടെ സേവനങ്ങൾ", kn: "ನಮ್ಮ ಸೇವೆಗಳು", bn: "আমাদের সেবা", ur: "ہماری خدمات", ar: "خدماتنا", fa: "خدمات ما", tr: "Hizmetlerimiz", ru: "Наши услуги", zh: "我们的服务", ja: "サービス", ko: "서비스", th: "บริการของเรา", vi: "Dịch vụ", id: "Layanan Kami", ms: "Perkhidmatan Kami", tl: "Aming Serbisyo", sw: "Huduma Zetu", nl: "Onze Diensten", pl: "Nasze Usługi", el: "Υπηρεσίες" },
  "nav.job_seekers": { en: "Job Seekers", es: "Buscadores de Empleo", fr: "Chercheurs d'Emploi", de: "Stellensuchende", it: "Cercatori di Lavoro", pt: "Procuradores de Emprego", hi: "नौकरी तलाशने वाले", ta: "வேலை தேடுபவர்கள்", te: "ఉద్యోగ అన్వేషకులు", ml: "തൊഴിൽ അന്വേഷകർ", kn: "ಉದ್ಯೋಗ ಹುಡುಕುವವರು", bn: "চাকরি প্রার্থী", ur: "ملازمت کے متلاشی", ar: "الباحثون عن عمل", fa: "جویای کار", tr: "İş Arayanlar", ru: "Соискатели", zh: "求职者", ja: "求職者", ko: "구직자", th: "ผู้หางาน", vi: "Người tìm việc", id: "Pencari Kerja", ms: "Pencari Kerja", tl: "Manghahanap ng Trabaho", sw: "Watafuta Kazi", nl: "Werkzoekenden", pl: "Szukający Pracy", el: "Αναζητούντες Εργασία" },
  "nav.job_referrer": { en: "Job Referrer", es: "Referidor de Empleo", fr: "Référent d'Emploi", de: "Stellenvermittler", it: "Referente di Lavoro", pt: "Referenciador de Emprego", hi: "नौकरी संदर्भकर्ता", ta: "வேலை குறிப்பிடுபவர்", te: "ఉద్యోగ రెఫరర్", ml: "തൊഴിൽ റഫറർ", kn: "ಉದ್ಯೋಗ ರೆಫರರ್", bn: "চাকরি রেফারার", ur: "ملازمت کا حوالہ دینے والا", ar: "مرشح وظائف", fa: "ارجاع‌دهنده شغل", tr: "İş Yönlendirici", ru: "Реферал", zh: "推荐人", ja: "紹介者", ko: "채용추천", th: "ผูแนะนำงาน", vi: "Người giới thiệu việc", id: "Perujuk Kerja", ms: "Perujuk Kerja", tl: "Tagapag-Refer ng Trabaho", sw: "Mrejeshaji wa Kazi", nl: "Vacatureverstrekker", pl: "Polecający Pracę", el: "Παραπέμποντας" },
  "nav.current_vacancy": { en: "Current Vacancies", es: "Vacantes Actuales", fr: "Postes Vacants", de: "Aktuelle Stellen", it: "Posti Vacanti", pt: "Vagas Atuais", hi: "वर्तमान रिक्तियां", ta: "தற்போதைய வெற்றிடங்கள்", te: "ప్రస్తుత ఖాళీలు", ml: "നിലവിലെ ഒഴിവുകൾ", kn: "ಪ್ರಸ್ತುತ ಖಾಲಿ ಹುದ್ದೆಗಳು", bn: "বর্তমান শূন্যপদ", ur: "موجودہ خالی آسامیاں", ar: "الوظائف الشاغرة", fa: "موقعیت‌های خالی", tr: "Güncel İlanlar", ru: "Текущие вакансии", zh: "当前空缺", ja: "現在の空席", ko: "현재 채용공고", th: "ตำแหน่งว่าง", vi: "Vị trí trống", id: "Lowongan Saat Ini", ms: "Kekosongan Semasa", tl: "Kasalukuyang Bakante", sw: "Nafasi za Sasa", nl: "Huidige Vacatures", pl: "Aktualne Oferty", el: "Τρέχουσες Θέσεις" },
  "nav.agency": { en: "Agency", es: "Agencia", fr: "Agence", de: "Agentur", it: "Agenzia", pt: "Agência", hi: "एजेंसी", ta: "நிறுவனம்", te: "ఏజెన్సీ", ml: "ഏജൻസി", kn: "ಏಜೆನ್ಸಿ", bn: "এজেন্সি", ur: "ایجنسی", ar: "الوكالة", fa: "آژانس", tr: "Ajans", ru: "Агентство", zh: "机构", ja: "エージェンシー", ko: "에이전시", th: "เอเจนซี่", vi: "Đại lý", id: "Agen", ms: "Agensi", tl: "Ahensiya", sw: "Shirika", nl: "Bureau", pl: "Agencja", el: "Πρακτορείο" },
  "nav.contact": { en: "Contact", es: "Contacto", fr: "Contact", de: "Kontakt", it: "Contatto", pt: "Contato", hi: "संपर्क", ta: "தொடர்பு", te: "సంప్రదించండి", ml: "ബന്ധപ്പെടുക", kn: "ಸಂಪರ್ಕ", bn: "যোগাযোগ", ur: "رابطہ", ar: "اتصل بنا", fa: "تماس", tr: "İletişim", ru: "Контакты", zh: "联系", ja: "お問い合わせ", ko: "연락처", th: "ติดต่อ", vi: "Liên hệ", id: "Kontak", ms: "Hubungi", tl: "Makipag-ugnayan", sw: "Wasiliana", nl: "Contact", pl: "Kontakt", el: "Επικοινωνία" },

  // Hero section
  "hero.title": { en: "Find Your Dream Career, Anywhere in the World", es: "Encuentra tu Carrera de Ensueño en Cualquier Lugar del Mundo", fr: "Trouvez Votre Carrière de Rêve, N'importe Où dans le Monde", de: "Finden Sie Ihre Traumkarriere, Überall auf der Welt", it: "Trova la Tua Carriera dei Sogni, Ovunque nel Mondo", pt: "Encontre Sua Carreira dos Sonhos, Em Qualquer Lugar do Mundo", hi: "दुनिया में कहीं भी अपने सपनों का करियर खोजें", ta: "உலகில் எங்கும் உங்கள் கனவு வேலையைக் கண்டுபிடியுங்கள்", te: "ప్రపంచంలో ఎక్కడైనా మీ కల వృత్తిని కనుగొనండి", ml: "ലോകത്ത് എവിടെയും നിങ്ങളുടെ സ്വപ്ന കരിയർ കണ്ടെത്തുക", kn: "ಪ್ರಪಂಚದಲ್ಲಿ ಎಲ್ಲಿಯಾದರೂ ನಿಮ್ಮ ಕನಸಿನ ವೃತ್ತಿಯನ್ನು ಹುಡುಕಿ", bn: "বিশ্বের যেকোনো স্থানে আপনার স্বপ্নের ক্যারিয়ার খুঁজুন", ur: "دنیا میں کہیں بھی اپنے خواب کا کیریئر تلاش کریں", ar: "اعثر على مسيرة أحلامك في أي مكان في العالم", fa: "حرفه رویایی خود را در هر کجای دنیا پیدا کنید", tr: "Hayalinizdeki Kariyeri Dünyanın Her Yerinde Bulun", ru: "Найдите Карьеру Мечты в Любой Точке Мира", zh: "在世界任何地方找到您梦想的职业", ja: "世界中どこでも夢のキャリアを見つけよう", ko: "세계 어디서든 꿈의 커리어를 찾으세요", th: "ค้นหาอาชีพในฝันที่ใดก็ได้ในโลก", vi: "Tìm Kiếm Nghề Nghiệp Mơ Ước Bất Kỳ Nơi Đâu Trên Thế Giới", id: "Temukan Karier Impian Anda di Mana Saja di Dunia", ms: "Cari Kerjaya Impian Anda Di Mana Sahaja Di Dunia", tl: "Hanapin ang Iyong Karera ng Pangarap Kahit Saan sa Mundo", sw: "Pata Kazi ya Ndoto Yako Popote Duniani", nl: "Vind Uw Droombaan, Overal ter Wereld", pl: "Znajdź Wymarzoną Karierę, Gdziekolwiek na Świecie", el: "Βρείτε την Καριέρα των Ονείρων σας, Οπουδήποτε στον Κόσμο" },
  "hero.subtitle": { en: "GET YOUR DREAMS connects ambitious talent with leading employers across the globe. Whether you're seeking opportunity or looking to hire, your journey starts here.", es: "GET YOUR DREAMS conecta talento ambicioso con empleadores líderes en todo el mundo. Ya sea que busques oportunidades o quieras contratar, tu viaje comienza aquí.", fr: "GET YOUR DREAMS relie les talents ambitieux aux employeurs leaders à travers le monde. Que vous cherchiez une opportunité ou que vous souhaitiez recruter, votre voyage commence ici.", de: "GET YOUR DREAMS verbindet ehrgeizige Talente mit führenden Arbeitgebern weltweit. Ob Sie eine Gelegenheit suchen oder einstellen möchten, Ihre Reise beginnt hier.", hi: "GET YOUR DREAMS महत्वाकांक्षी प्रतिभाओं को दुनिया भर के प्रमुख नियोक्ताओं से जोड़ता है। चाहे आप अवसर खोज रहे हों या भर्ती करना चाहते हों, आपकी यात्रा यहीं से शुरू होती है।", ar: "GET YOUR DREAMS تربط المواهب الطموحة بأصحاب العمل الرائدين حول العالم. سواء كنت تبحث عن فرصة أو ترغب في التوظيف، رحلتك تبدأ هنا.", ru: "GET YOUR DREAMS связывает амбициозные таланты с ведущими работодателями по всему миру. Независимо от того, ищете ли вы возможности или хотите нанять, ваше путешествие начинается здесь.", zh: "GET YOUR DREAMS 将有抱负的人才与全球领先雇主连接起来。无论您是在寻找机会还是想要招聘，您的旅程从这里开始。", ja: "GET YOUR DREAMSは野心的な人材と世界のトップ雇用者を結びます。機会を探すにしても採用するにしても、あなたの旅はここから始まります。", ko: "GET YOUR DREAMS는 야심 찬 인재를 전 세계 선도 고용주와 연결합니다. 기회를 찾든 채용을 원하든, 여정은 여기서 시작됩니다." },
  "hero.badge": { en: "Global Recruitment Excellence", es: "Excelencia en Reclutamiento Global", fr: "Excellence en Recrutement Mondial", de: "Globale Rekrutierungsexzellenz", hi: "वैश्विक भर्ती उत्कृष्टता", ar: "تميز عالمي في التوظيف", ru: "Глобальное Рекрутинговое Совершенство", zh: "全球招聘卓越", ja: "グローバル採用の卓越性", ko: "글로벌 채용 우수성" },
  "hero.cta.seeker": { en: "I'm a Job Seeker", es: "Soy Buscador de Empleo", fr: "Je Cherche un Emploi", de: "Ich Suche eine Stelle", hi: "मैं नौकरी तलाश रहा हूं", ar: "أنا باحث عن عمل", ru: "Я Ищу Работу", zh: "我是求职者", ja: "求職者です", ko: "구직자입니다" },
  "hero.cta.vacancy": { en: "View Vacancies", es: "Ver Vacantes", fr: "Voir les Postes", de: "Stellen Ansehen", hi: "रिक्तियां देखें", ar: "عرض الوظائف الشاغرة", ru: "Смотреть Вакансии", zh: "查看空缺", ja: "空席を見る", ko: "채용공고 보기" },

  // Section titles
  "section.disclaimer.title": { en: "Disclaimer", es: "Aviso Legal", fr: "Avertissement", de: "Haftungsausschluss", hi: "अस्वीकरण", ar: "إخلاء مسؤولية", ru: "Отказ от ответственности", zh: "免责声明", ja: "免責事項", ko: "면책 조항" },
  "section.our_services.title": { en: "Our Services", es: "Nuestros Servicios", fr: "Nos Services", de: "Unsere Dienstleistungen", hi: "हमारी सेवाएं", ar: "خدماتنا", ru: "Наши услуги", zh: "我们的服务", ja: "サービス", ko: "서비스" },
  "section.job_seekers.title": { en: "For Job Seekers", es: "Para Buscadores de Empleo", fr: "Pour les Chercheurs d'Emploi", de: "Für Stellensuchende", hi: "नौकरी तलाशने वालों के लिए", ar: "للباحثين عن عمل", ru: "Для Соискателей", zh: "求职者专区", ja: "求職者の方へ", ko: "구직자를 위하여" },
  "section.job_referrer.title": { en: "For Job Referrers", es: "Para Referidores", fr: "Pour les Référents", de: "Für Stellenvermittler", hi: "नौकरी संदर्भकर्ताओं के लिए", ar: "لمرشحي الوظائف", ru: "Для Рефералов", zh: "推荐人专区", ja: "紹介者の方へ", ko: "채용추천인을 위하여" },
  "section.agency.title": { en: "For Agencies", es: "Para Agencias", fr: "Pour les Agences", de: "Für Agenturen", hi: "एजेंसियों के लिए", ar: "للوكالات", ru: "Для Агентств", zh: "机构专区", ja: "エージェンシーの方へ", ko: "에이전시를 위하여" },
  "section.contact.title": { en: "Contact Us", es: "Contáctenos", fr: "Contactez-Nous", de: "Kontaktieren Sie Uns", hi: "हमसे संपर्क करें", ar: "اتصل بنا", ru: "Свяжитесь с Нами", zh: "联系我们", ja: "お問い合わせ", ko: "문의하기" },

  // CTA labels
  "cta.learn_more": { en: "Learn more", es: "Más información", fr: "En savoir plus", de: "Mehr erfahren", hi: "और जानें", ar: "اعرف المزيد", ru: "Узнать больше", zh: "了解更多", ja: "詳しく見る", ko: "자세히 보기" },
  "cta.apply_now": { en: "Apply now", es: "Aplicar ahora", fr: "Postuler", de: "Jetzt bewerben", hi: "अभी आवेदन करें", ar: "قدم الآن", ru: "Подать заявку", zh: "立即申请", ja: "今すぐ応募", ko: "지금 지원" },
  "cta.post_job": { en: "Post a job", es: "Publicar empleo", fr: "Publier un emploi", de: "Stelle ausschreiben", hi: "नौकरी पोस्ट करें", ar: "انشر وظيفة", ru: "Разместить вакансию", zh: "发布职位", ja: "求人を投稿", ko: "채용공고 등록" },
  "cta.register_agency": { en: "Register agency", es: "Registrar agencia", fr: "Enregistrer agence", de: "Agentur registrieren", hi: "एजेंसी पंजीकृत करें", ar: "تسجيل الوكالة", ru: "Зарегистрировать агентство", zh: "注册机构", ja: "エージェンシー登録", ko: "에이전시 등록" },
  "cta.contact_us": { en: "Contact us", es: "Contáctenos", fr: "Contactez-nous", de: "Kontaktieren Sie uns", hi: "हमसे संपर्क करें", ar: "اتصل بنا", ru: "Связаться с нами", zh: "联系我们", ja: "お問い合わせ", ko: "문의하기" },

  // Footer
  "footer.quick_links": { en: "Quick Links", es: "Enlaces Rápidos", fr: "Liens Rapides", de: "Schnelllinks", hi: "त्वरित लिंक", ar: "روابط سريعة", ru: "Быстрые ссылки", zh: "快速链接", ja: "クイックリンク", ko: "빠른 링크" },
  "footer.contact": { en: "Contact", es: "Contacto", fr: "Contact", de: "Kontakt", hi: "संपर्क", ar: "اتصل", ru: "Контакты", zh: "联系", ja: "お問い合わせ", ko: "연락처" },
  "footer.legal": { en: "Legal", es: "Legal", fr: "Légal", de: "Rechtliches", hi: "कानूनी", ar: "قانوني", ru: "Правовая информация", zh: "法律", ja: "法的事項", ko: "법적 고지" },
  "footer.terms": { en: "Terms & Conditions", es: "Términos y Condiciones", fr: "Conditions Générales", de: "Allgemeine Geschäftsbedingungen", hi: "नियम और शर्तें", ar: "الشروط والأحكام", ru: "Условия и Положения", zh: "条款与条件", ja: "利用規約", ko: "이용약관" },
  "footer.privacy": { en: "Privacy Policy", es: "Política de Privacidad", fr: "Politique de Confidentialité", de: "Datenschutzrichtlinie", hi: "गोपनीयता नीति", ar: "سياسة الخصوصية", ru: "Политика Конфиденциальности", zh: "隐私政策", ja: "プライバシーポリシー", ko: "개인정보 보호정책" },
  "footer.support": { en: "Support", es: "Soporte", fr: "Support", de: "Support", hi: "सहायता", ar: "الدعم", ru: "Поддержка", zh: "支持", ja: "サポート", ko: "지원" },
  "footer.connect": { en: "Connect with us", es: "Conéctese con nosotros", fr: "Connectez-vous avec nous", de: "Verbinden Sie sich mit uns", hi: "हमसे जुड़ें", ar: "تواصل معنا", ru: "Свяжитесь с нами", zh: "与我们联系", ja: "お問い合わせ", ko: "우리와 연결" },

  // Edit mode
  "edit.active": { en: "Edit mode active — click any text or image to edit. Changes save automatically.", es: "Modo edición activo — haga clic en cualquier texto o imagen para editar.", fr: "Mode édition actif — cliquez sur n'importe quel texte ou image.", de: "Bearbeitungsmodus aktiv — klicken Sie auf Text oder Bild zum Bearbeiten.", hi: "संपादन मोड सक्रिय — संपादित करने के लिए किसी भी टेक्स्ट या छवि पर क्लिक करें।", ar: "وضع التحرير نشط — انقر على أي نص أو صورة للتحرير.", ru: "Режим редактирования активен — нажмите на текст или изображение для редактирования.", zh: "编辑模式已激活 — 点击任何文本或图像进行编辑。", ja: "編集モードがアクティブ — テキストや画像をクリックして編集。", ko: "편집 모드 활성 — 텍스트나 이미지를 클릭하여 편집하세요." },
};

export function t(key: string, lang: string): string | undefined {
  return translations[key]?.[lang] ?? translations[key]?.["en"];
}

export function useTranslation(lang: string) {
  return (key: string, fallback?: string): string => t(key, lang) ?? fallback ?? key;
}
