-- #################################################################
-- ###                                                           ###
-- ###        ROW LEVEL SECURITY (RLS) POLICIES FOR TABLES       ###
-- ###                                                           ###
-- #################################################################
--
-- These policies control who can access and modify data in your tables.
--
-- How to use:
-- 1. Go to your Supabase project dashboard.
-- 2. In the left sidebar, click on "SQL Editor".
-- 3. Click "New query".
-- 4. Copy and paste the content of this file into the editor.
-- 5. Click "RUN".

-- #################################################################
-- ###              TABLE SCHEMAS                                ###
-- #################################################################

-- Create contacts table
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  subject TEXT,
  details TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Create job_seekers table
CREATE TABLE IF NOT EXISTS public.job_seekers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  designation TEXT,
  expected_salary TEXT,
  salary_currency TEXT,
  experience TEXT,
  expected_country TEXT,
  current_position TEXT,
  native_country TEXT,
  cv_url TEXT,
  cover_letter_url TEXT,
  passport_url TEXT,
  certificates_url TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Create job_referrers table
CREATE TABLE IF NOT EXISTS public.job_referrers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  job_position TEXT,
  company_name TEXT,
  salary TEXT,
  salary_currency TEXT,
  location TEXT,
  job_expiry_date DATE,
  job_type TEXT,
  responsibilities TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Create agencies table
CREATE TABLE IF NOT EXISTS public.agencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  agency_name TEXT,
  contact_number TEXT,
  email TEXT,
  job_position TEXT,
  agency_address TEXT,
  location TEXT,
  company_name TEXT,
  salary TEXT,
  salary_currency TEXT,
  job_expiry_date DATE,
  job_type TEXT,
  responsibilities TEXT,
  license_url TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Create vacancies table
CREATE TABLE IF NOT EXISTS public.vacancies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  position TEXT,
  company_name TEXT,
  location TEXT,
  salary TEXT,
  salary_currency TEXT,
  experience TEXT,
  job_type TEXT,
  responsibilities TEXT,
  is_international BOOLEAN,
  industry TEXT,
  active BOOLEAN DEFAULT true
);

-- Create vacancy_applications table
CREATE TABLE IF NOT EXISTS public.vacancy_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  vacancy_id BIGINT REFERENCES public.vacancies(id),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  experience TEXT,
  cv_url TEXT,
  cover_letter_url TEXT,
  certificate_url TEXT,
  passport_url TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- #################################################################
-- ###              TABLE: user_roles                            ###
-- #################################################################
--
-- This table links users from `auth.users` to their roles.
--
-- 1. Create an ENUM type for roles to ensure data consistency.
CREATE TYPE public.user_role AS ENUM ('admin');

-- 2. Create the user_roles table.
CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  role user_role NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS for the table.
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- 4. Users can see their own roles.
CREATE POLICY "Allow user to see their own roles" ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id);


-- #################################################################
-- ###        HELPER FUNCTION TO CHECK FOR ADMIN ROLE            ###
-- #################################################################
--
-- This function checks if the currently logged-in user has the 'admin' role.
-- It's used in the policies below to grant admins full access.
--
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1
    FROM user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- #################################################################
-- ###        RLS POLICIES THAT DEPEND ON is_admin()             ###
-- #################################################################
-- Admins can see and manage all roles.
CREATE POLICY "Allow admin to manage roles" ON public.user_roles FOR ALL USING (is_admin()) WITH CHECK (is_admin());

-- #################################################################
-- ###                 TABLE: contacts                           ###
-- #################################################################

-- 1. Enable RLS for the table
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- 2. Allow anyone to submit the contact form
CREATE POLICY "Allow public insert for contacts" ON public.contacts FOR INSERT WITH CHECK (true);

-- 3. Allow admins to see, update, and delete all contact submissions
CREATE POLICY "Allow admin full access for contacts" ON public.contacts FOR ALL USING (is_admin());


-- #################################################################
-- ###                 TABLE: job_seekers                        ###
-- #################################################################

-- 1. Enable RLS for the table
ALTER TABLE public.job_seekers ENABLE ROW LEVEL SECURITY;

-- 2. Allow anyone to submit the job seeker form
CREATE POLICY "Allow public insert for job_seekers" ON public.job_seekers FOR INSERT WITH CHECK (true);

-- 3. Allow admins to see, update, and delete all job seeker submissions
CREATE POLICY "Allow admin full access for job_seekers" ON public.job_seekers FOR ALL USING (is_admin());


-- #################################################################
-- ###                 TABLE: job_referrers                      ###
-- #################################################################

-- 1. Enable RLS for the table
ALTER TABLE public.job_referrers ENABLE ROW LEVEL SECURITY;

-- 2. Allow anyone to submit the job referrer form
CREATE POLICY "Allow public insert for job_referrers" ON public.job_referrers FOR INSERT WITH CHECK (true);

-- 3. Allow admins to see, update, and delete all job referrer submissions
CREATE POLICY "Allow admin full access for job_referrers" ON public.job_referrers FOR ALL USING (is_admin());


-- #################################################################
-- ###                 TABLE: agencies                           ###
-- #################################################################

-- 1. Enable RLS for the table
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;

-- 2. Allow anyone to submit the agency form
CREATE POLICY "Allow public insert for agencies" ON public.agencies FOR INSERT WITH CHECK (true);

-- 3. Allow admins to see, update, and delete all agency submissions
CREATE POLICY "Allow admin full access for agencies" ON public.agencies FOR ALL USING (is_admin());


-- #################################################################
-- ###              TABLE: vacancy_applications                  ###
-- #################################################################

-- 1. Enable RLS for the table
ALTER TABLE public.vacancy_applications ENABLE ROW LEVEL SECURITY;

-- 2. Allow anyone to submit a job application
CREATE POLICY "Allow public insert for vacancy_applications" ON public.vacancy_applications FOR INSERT WITH CHECK (true);

-- 3. Allow admins to see, update, and delete all job applications
CREATE POLICY "Allow admin full access for vacancy_applications" ON public.vacancy_applications FOR ALL USING (is_admin());


-- #################################################################
-- ###                 TABLE: vacancies                          ###
-- #################################################################

-- 1. Enable RLS for the table
ALTER TABLE public.vacancies ENABLE ROW LEVEL SECURITY;

-- 2. Allow anyone to view active vacancies
CREATE POLICY "Allow public read for active vacancies" ON public.vacancies FOR SELECT USING (active = true);

-- 3. Allow admins to manage all vacancies
CREATE POLICY "Allow admin full access for vacancies" ON public.vacancies FOR ALL USING (is_admin());