-- #################################################################
-- ###                                                           ###
-- ###        ROW LEVEL SECURITY (RLS) POLICIES FOR TABLES       ###
-- ###                                                           ###
-- #################################################################

-- Table: contacts
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  subject TEXT,
  details TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Table: job_seekers
CREATE TABLE IF NOT EXISTS public.job_seekers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  designation TEXT,
  expected_salary TEXT,
  salary_currency TEXT,
  experience TEXT,
  expected_country TEXT,
  current_position TEXT,
  native_country TEXT,
  cv_url TEXT,
  cover_letter_url TEXT,
  passport_url TEXT,
  certificates_url TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Table: job_referrers
CREATE TABLE IF NOT EXISTS public.job_referrers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  job_position TEXT,
  company_name TEXT,
  salary TEXT,
  salary_currency TEXT,
  location TEXT,
  job_expiry_date DATE,
  job_type TEXT,
  responsibilities TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Table: agencies
CREATE TABLE IF NOT EXISTS public.agencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  agency_name TEXT,
  contact_number TEXT,
  email TEXT,
  job_position TEXT,
  agency_address TEXT,
  location TEXT,
  company_name TEXT,
  salary TEXT,
  salary_currency TEXT,
  job_expiry_date DATE,
  job_type TEXT,
  responsibilities TEXT,
  license_url TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Table: vacancies
CREATE TABLE IF NOT EXISTS public.vacancies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  position TEXT,
  company_name TEXT,
  location TEXT,
  salary TEXT,
  salary_currency TEXT,
  experience TEXT,
  job_type TEXT,
  responsibilities TEXT,
  is_international BOOLEAN,
  industry TEXT,
  active BOOLEAN DEFAULT true
);

-- Table: vacancy_applications
CREATE TABLE IF NOT EXISTS public.vacancy_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  vacancy_id BIGINT REFERENCES public.vacancies(id),
  name TEXT,
  contact_number TEXT,
  email TEXT,
  experience TEXT,
  cv_url TEXT,
  cover_letter_url TEXT,
  certificate_url TEXT,
  passport_url TEXT,
  phone_verified BOOLEAN,
  email_verified BOOLEAN
);

-- Table: user_roles
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE public.user_role AS ENUM ('admin');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  role user_role NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Helper function with immutable search_path and restricted execute
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = auth.uid() AND (role = 'admin'::public.user_role OR role::text = 'admin')
  );
$$;

REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- Policies for user_roles
DROP POLICY IF EXISTS "Allow user to see their own roles" ON public.user_roles;
CREATE POLICY "Allow user to see their own roles" ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admin to manage roles" ON public.user_roles;
CREATE POLICY "Allow admin to manage roles" ON public.user_roles FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Policies for contacts
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert for contacts" ON public.contacts;
CREATE POLICY "Allow public insert for contacts" ON public.contacts FOR INSERT WITH CHECK (
  email IS NOT NULL AND length(trim(email)) > 3 AND email LIKE '%@%' AND name IS NOT NULL AND length(trim(name)) > 0
);
DROP POLICY IF EXISTS "Allow admin full access for contacts" ON public.contacts;
CREATE POLICY "Allow admin full access for contacts" ON public.contacts FOR ALL USING (public.is_admin());

-- Policies for job_seekers
ALTER TABLE public.job_seekers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert for job_seekers" ON public.job_seekers;
CREATE POLICY "Allow public insert for job_seekers" ON public.job_seekers FOR INSERT WITH CHECK (
  email IS NOT NULL AND length(trim(email)) > 3 AND email LIKE '%@%' AND name IS NOT NULL AND length(trim(name)) > 0
);
DROP POLICY IF EXISTS "Allow admin full access for job_seekers" ON public.job_seekers;
CREATE POLICY "Allow admin full access for job_seekers" ON public.job_seekers FOR ALL USING (public.is_admin());

-- Policies for job_referrers
ALTER TABLE public.job_referrers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert for job_referrers" ON public.job_referrers;
CREATE POLICY "Allow public insert for job_referrers" ON public.job_referrers FOR INSERT WITH CHECK (
  email IS NOT NULL AND length(trim(email)) > 3 AND email LIKE '%@%' AND name IS NOT NULL AND length(trim(name)) > 0
);
DROP POLICY IF EXISTS "Allow admin full access for job_referrers" ON public.job_referrers;
CREATE POLICY "Allow admin full access for job_referrers" ON public.job_referrers FOR ALL USING (public.is_admin());

-- Policies for agencies
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert for agencies" ON public.agencies;
CREATE POLICY "Allow public insert for agencies" ON public.agencies FOR INSERT WITH CHECK (
  email IS NOT NULL AND length(trim(email)) > 3 AND email LIKE '%@%' AND agency_name IS NOT NULL AND length(trim(agency_name)) > 0
);
DROP POLICY IF EXISTS "Allow admin full access for agencies" ON public.agencies;
CREATE POLICY "Allow admin full access for agencies" ON public.agencies FOR ALL USING (public.is_admin());

-- Policies for vacancy_applications
ALTER TABLE public.vacancy_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert for vacancy_applications" ON public.vacancy_applications;
CREATE POLICY "Allow public insert for vacancy_applications" ON public.vacancy_applications FOR INSERT WITH CHECK (
  email IS NOT NULL AND length(trim(email)) > 3 AND email LIKE '%@%' AND name IS NOT NULL AND length(trim(name)) > 0
);
DROP POLICY IF EXISTS "Allow admin full access for vacancy_applications" ON public.vacancy_applications;
CREATE POLICY "Allow admin full access for vacancy_applications" ON public.vacancy_applications FOR ALL USING (public.is_admin());

-- Policies for vacancies
ALTER TABLE public.vacancies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read for active vacancies" ON public.vacancies;
CREATE POLICY "Allow public read for active vacancies" ON public.vacancies FOR SELECT USING (active = true);
DROP POLICY IF EXISTS "Allow admin full access for vacancies" ON public.vacancies;
CREATE POLICY "Allow admin full access for vacancies" ON public.vacancies FOR ALL USING (public.is_admin());